### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by thuyD** [thuyD/channel#5]
Have Ali review user auth

**Comment by AM-Harris** [comment]
- [ ] When I try to log out, I get this error: "Uncaught Error: Given action "RECEIVE_ERRORS", reducer "session" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined." I was logged in looking at it before, so I can't log out to test logging in again

**Comment by AM-Harris** [comment]
- [ ] I don't actually see much to review on heroku. Did you push your recent work?

**Comment by AM-Harris** [comment]
- [ ] Have login/signup buttons on the landing page that take you to login/signup forms
- [ ] Have a demo login button. This is for a recruiter to be able to quickly interact with your site in a logged in state without having to fill in any forms. You will need user seed to be demo, and the button should just log them in.
- [ ] successful signup/login should redirect to a home page/story index/whatever medium does. You don't need anything there yet but a logout button
- [ ] nice work on the errors!

**Comment by AM-Harris** [comment]
- [ ]  Error styling and position
- [ ] At some point you'll need to style your header and log out button. I recommend doing it now as part of auth.

**Comment by AM-Harris** [comment]
Looks good to me!
